### PR TITLE
Upgrade cairo version to 2.6.3

### LINKED ISSUE #35: Udate Koji to Cairo 2.6.x
We need to update Koji to scarb/cairo 2.6.x. It currently supports scarb 2.3.1.

### PR DESCRIPTION
**Pull request by AryanGodara**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: Resolves #35 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by caseywescott — COMMENTED** [review]
I'm curious, why add the '_' character before msg names like SetTempo to _SetTempo? Is that a style thing or something new to cairo 2.6?

**Comment by AryanGodara** [comment]
> I'm curious, why add the '_' character before msg names like SetTempo to _SetTempo? Is that a style thing or something new to cairo 2.6?

It's because in the match case, SetTempo was used, but it's not used.
```cairo
Message::SET_TEMPO(_SetTempo) => { eventlist.append(*currentevent); },
```

We can also write 
```cairo
Message::SET_TEMPO(_) => { eventlsit.append(...); },
```

but I thought to preserve the correct variable name, in case we use it in future

**Review by caseywescott — COMMENTED** [review]
In the TG you said you were getting some warnings like this: 
Some(varName) => { ...varName not used here... } // So compiler said to use _varName if it's not being used
Thanks for the explanation in the previous comment... now that you changed those, are these warnings gone?

**Comment by AryanGodara** [comment]
> In the TG you said you were getting some warnings like this: Some(varName) => { ...varName not used here... } // So compiler said to use _varName if it's not being used Thanks for the explanation in the previous comment... now that you changed those, are these warnings gone?

Yes, all warnings and errors are gone now :D

**Comment by caseywescott** [comment]
This looks good to me! I'll merge shortly! I do get the following unused variables in cubit but everything runs well and doesn't affect Koji:

Unused variable. Consider ignoring by prefixing with `_`.
 --> /Users/caseywescott/Library/Caches/com.swmansion.scarb/registry/git/checkouts/cubit-k9rijvovof89o/6275608/src/f64/math/ops.cairo:209:10
    let (div, rem) = core::integer::u64_safe_divmod(b.mag, u64_as_non_zero(ONE));
         ^*^

warn: Unused variable. Consider ignoring by prefixing with `_`.
 --> /Users/caseywescott/Library/Caches/com.swmansion.scarb/registry/git/checkouts/cubit-k9rijvovof89o/6275608/src/f128/math/ops.cairo:229:10
    let (div_u128, rem_u128) = _split_unsigned(b);
         ^******^

**Review by caseywescott — APPROVED** [review]
Everything looks great and runs well locally for me. I appreciate the optimizations in core.cairo.

**Comment by AryanGodara** [comment]
> This looks good to me! I'll merge shortly! I do get the following unused variables in cubit but everything runs well and doesn't affect Koji:
> 
> Unused variable. Consider ignoring by prefixing with `_`. --> /Users/caseywescott/Library/Caches/com.swmansion.scarb/registry/git/checkouts/cubit-k9rijvovof89o/6275608/src/f64/math/ops.cairo:209:10 let (div, rem) = core::integer::u64_safe_divmod(b.mag, u64_as_non_zero(ONE)); ^*^
> 
> warn: Unused variable. Consider ignoring by prefixing with `_`. --> /Users/caseywescott/Library/Caches/com.swmansion.scarb/registry/git/checkouts/cubit-k9rijvovof89o/6275608/src/f128/math/ops.cairo:229:10 let (div_u128, rem_u128) = _split_unsigned(b); ^******^

Oh, I'm sorry. I think I missed those 😅 
Is it okay if I quickly open a new PR to fix these as well? (Not part of the ODHack, just a quick fix :D )

**Comment by caseywescott** [comment]
Sure you can! I already pushed the last round of commits so you might need
to make a new branch...

**Comment by AryanGodara** [comment]
@caseywescott It seems to be a warning in some library code, which isn't part of our repo.
So, maybe we don't need to fix this? Since, it can't be pushed to git anyways 😅

**Comment by caseywescott** [comment]
Sounds good, everything is functioning properly so all good! Thanks for
giving this a second look!!!

**Pull request merged**
